import type { Language } from "../types";

const LANGUAGES: Language[] = [
  {
    name: "Auto",
    mode: "auto",
  },
  {
    name: "Bash",
    hljs: "bash",
    mode: "shell",
    path: "shell/shell",
  },
  {
    name: "C++",
    hljs: "cpp",
    mode: "text/x-c++src",
    path: "clike/clike",
  },
  {
    name: "C#",
    hljs: "csharp",
    mode: "text/x-csharp",
    path: "clike/clike",
  },
  {
    name: "Clojure",
    hljs: "clojure",
    mode: "text/x-clojure",
    path: "clojure/clojure",
  },
  {
    name: "CoffeeScript",
    hljs: "coffeescript",
    mode: "text/x-coffeescript",
    path: "coffeescript/coffeescript",
  },
  {
    name: "Crystal",
    hljs: "crystal",
    mode: "text/x-crystal",
    path: "crystal/crystal",
  },
  {
    name: "CSS",
    hljs: "css",
    mode: "text/css",
    path: "css/css",
  },
  {
    name: "D",
    hljs: "d",
    mode: "text/x-d",
    path: "d/d",
  },
  {
    name: "Dart",
    hljs: "dart",
    mode: "application/dart",
    path: "dart/dart",
  },
  {
    name: "Diff",
    hljs: "diff",
    mode: "text/x-diff",
    path: "diff/diff",
  },
  {
    name: "Docker",
    hljs: "dockerfile",
    mode: "dockerfile",
    path: "dockerfile/dockerfile",
  },
  {
    name: "Elm",
    hljs: "elm",
    mode: "text/x-elm",
    path: "elm/elm",
  },
  {
    name: "Erlang",
    hljs: "erlang",
    mode: "text/x-erlang",
    path: "erlang/erlang",
  },
  {
    name: "Fortran",
    hljs: "fortran",
    mode: "text/x-fortran",
    path: "fortran/fortran",
  },
  {
    name: "F#",
    hljs: "fsharp",
    mode: "text/x-fsharp",
    path: "mllike/mllike",
  },
  {
    name: "Gherkin",
    hljs: "gherkin",
    mode: "text/x-feature",
    path: "gherkin/gherkin",
  },
  {
    name: "Go",
    hljs: "go",
    mode: "text/x-go",
    path: "go/go",
  },
  {
    name: "Groovy",
    hljs: "groovy",
    mode: "text/x-groovy",
    path: "groovy/groovy",
  },
  {
    name: "Haskell",
    hljs: "haskell",
    mode: "text/x-haskell",
    path: "haskell/haskell",
  },
  {
    name: "HTTP",
    hljs: "http",
    mode: "message/http",
    path: "http/http",
  },
  {
    name: "HTML",
    hljs: "xml",
    mode: "text/html",
    path: "xml/xml",
  },
  {
    name: "Java",
    hljs: "java",
    mode: "text/x-java",
    path: "clike/clike",
  },
  {
    name: "JavaScript",
    hljs: "javascript",
    mode: "text/javascript",
    path: "javascript/javascript",
  },
  {
    name: "JSON",
    hljs: "json",
    mode: "application/json",
    path: "javascript/javascript",
  },
  {
    name: "JSX",
    mode: "text/jsx",
    path: "jsx/jsx",
  },
  {
    name: "Julia",
    hljs: "julia",
    mode: "text/x-julia",
    path: "julia/julia",
  },
  {
    name: "Kotlin",
    hljs: "kotlin",
    mode: "text/x-kotlin",
    path: "clike/clike",
  },
  {
    name: "LaTeX",
    hljs: "latex",
    mode: "text/text/x-stex",
    path: "stex/stex",
  },
  {
    name: "Lisp",
    hljs: "lisp",
    mode: "text/x-common-lisp",
    path: "commonlisp/commonlisp",
  },
  {
    name: "Lua",
    hljs: "lua",
    mode: "text/x-lua",
    path: "lua/lua",
  },
  {
    name: "Markdown",
    hljs: "markdown",
    mode: "text/x-markdown",
    path: "markdown/markdown",
  },
  {
    name: "Mathematica",
    hljs: "mathematica",
    mode: "text/x-mathematica",
    path: "mathematica/mathematica",
  },
  {
    name: "MATLAB/Octave",
    hljs: "matlab",
    mode: "text/x-octave",
    path: "octave/octave",
  },
  {
    name: "NGINX",
    hljs: "nginx",
    mode: "text/x-nginx-conf",
    path: "nginx/nginx",
  },
  {
    name: "Objective C",
    hljs: "objectivec",
    mode: "text/x-objectivec",
    path: "clike/clike",
  },
  {
    name: "OCaml",
    hljs: "ocaml",
    mode: "text/x-ocaml",
    path: "mllike/mllike",
  },
  {
    name: "Perl",
    hljs: "perl",
    mode: "text/x-perl",
    path: "perl/perl",
  },
  {
    name: "PHP",
    hljs: "php",
    mode: "application/x-httpd-php",
    path: "php/php",
  },
  {
    name: "PowerShell",
    hljs: "powershell",
    mode: "application/x-powershell",
    path: "powershell/powershell",
  },
  {
    name: "Python",
    hljs: "python",
    mode: "text/x-python",
    path: "python/python",
  },
  {
    name: "R",
    hljs: "r",
    mode: "text/x-rsrc",
    path: "r/r",
  },
  {
    name: "Ruby",
    hljs: "ruby",
    mode: "text/x-ruby",
    path: "ruby/ruby",
  },
  {
    name: "Rust",
    hljs: "rust",
    mode: "text/x-rustsrc",
    path: "rust/rust",
  },
  {
    name: "Scala",
    hljs: "scala",
    mode: "text/x-scala",
    path: "clike/clike",
  },
  {
    name: "SCSS",
    hljs: "scss",
    mode: "text/x-scss",
    path: "css/css",
  },
  {
    name: "Smalltalk",
    hljs: "smalltalk",
    mode: "text/x-stsrc",
    path: "smalltalk/smalltalk",
  },
  {
    name: "SQL",
    hljs: "sql",
    mode: "text/x-sql",
    path: "sql/sql",
  },
  {
    name: "Swift",
    hljs: "swift",
    mode: "text/x-swift",
    path: "swift/swift",
  },
  {
    name: "TOML",
    mode: "text/x-toml",
    path: "toml/toml",
  },
  {
    name: "TypeScript",
    hljs: "typescript",
    mode: "text/typescript",
    path: "javascript/javascript",
  },
  {
    name: "TSX",
    hljs: "typescript",
    mode: "text/typescript-jsx",
    path: "jsx/jsx",
  },
  {
    name: "Twig",
    hljs: "twig",
    mode: "text/x-twig",
    path: "twig/twig",
  },
  {
    name: "Verilog",
    hljs: "verilog",
    mode: "text/x-verilog",
    path: "verilog/verilog",
  },
  {
    name: "VHDL",
    hljs: "vhdl",
    mode: "text/x-vhdl",
    path: "vhdl/vhdl",
  },
  {
    name: "XQuery",
    hljs: "xquery",
    mode: "application/xquery",
    path: "xquery/xquery",
  },
  {
    name: "YAML",
    hljs: "yaml",
    mode: "text/x-yaml",
    path: "yaml/yaml",
  },
];

export default LANGUAGES;
