export const PEPINO_THEME = "PEPINO_THEME";
export const PEPINO_PADDING = "PEPINO_PADDING";
export const PEPINO_COLORED_BUTTONS = "PEPINO_COLORED_BUTTONS";
export const PEPINO_IMAGE_SCALE = "PEPINO_IMAGE_SCALE";
export const PEPINO_LINE_NUMBERS = "PEPINO_LINE_NUMBERS";
